### ISSUE TITLE
Release Schedule for IINA 1.3.2

### ISSUE THREAD

**Issue by uiryuu** [iina/iina#4379]
## Outstanding pull requests
- [x] https://github.com/iina/iina/pull/4356
- [x] https://github.com/iina/iina/pull/4368
- [x] https://github.com/iina/iina/pull/4360
- [x] https://github.com/iina/iina/pull/4369
- [x] https://github.com/iina/iina/pull/3993
- [ ] https://github.com/iina/iina/pull/4319
- [x] https://github.com/iina/iina/pull/4138
- [x] https://github.com/iina/iina/pull/4196
- [x] https://github.com/iina/iina/pull/4191
- [x] https://github.com/iina/iina/pull/4334

## Outstanding IINA issues
- [x] https://github.com/iina/iina/issues/3995

## Upstream issues
- [x] https://github.com/mpv-player/mpv/issues/11617
- [x] https://github.com/mpv-player/mpv/issues/11626

## Tasks
- [x] UI freeze
- [x] Sync translation from [Crowdin](https://crowdin.com/project/iina)
- [ ] Make release notes
- [ ] Generate `appcask.xml`
- [ ] Release build
- [ ] Upload binary to GitHub
- [x] Make release branch `release/1.3.2` 
- [x] Bump version
- [ ] Notarize
- [ ] Release branch merged back to develop/master branch in

**Comment by low-batt** [comment]
I created the `Outstanding IINA issues` section for release blockers found in `develop` and added #3995 to it.

Many thanks to @xjbeta for noticing and reporting the regression. I will try and find time to look into this today.
